server:
  port: 2025

management:
  security:  
    enabled: false 
    
spring:
  application:
    name: yerevan  
  jpa:
      database: MYSQL
      hibernate:
        ddl-auto: none
        dialect:  org.hibernate.dialect.MySQLDialect        
  datasource:
        url: ${MYSQL_URI:jdbc:mysql://127.0.0.1:3306/yerevan?zeroDateTimeBehavior=convertToNull&amp;useUnicode=yes&amp;characterEncoding=UTF-8)
        username: ${MYSQL_USER:carlos)
        password:  ${MYSQL_PASS:carlos)
        driver-class-name: com.mysql.jdbc.Driver    
